deeplog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls')), 
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail')
]

posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField()
    text = models.TextField(max_length=1000)

    class Meta:
        ordering = ['-date'] #Django magic

    def __str__(self):
        return f'{self.title} ({self.date})'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date'] #Django magic

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)
    text = models.TextField(max_length=500, default='A cool category!')

    def __str__(self):
        return f'{self.name}'

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'date',
            'text',
        ]
        labels = {
            'title': 'Title',
            'date': 'Date',
            'text': 'Text',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'date',
            'text',
        ]
        labels = {
            'author': 'User',
            'date': 'Date',
            'text': 'Comment',
        }

posts/views.py
from .models import Post, Comment, Category
from .forms import CommentForm
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/list.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

class PostCreateView(generic.CreateView):
    model = Post
    fields = ['title', 'date', 'text']
    template_name = 'posts/create.html'
    def get_success_url(self):
        return reverse('detail', args=(self.object.pk,))

class PostUpdateView(generic.UpdateView):
    model = Post
    fields = ['title', 'date', 'text']
    template_name = 'posts/update.html'
    def get_success_url(self):
        return reverse('detail', args=(self.object.pk,))

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    def get_success_url(self):
        return reverse('list')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_date =  form.cleaned_data['date']
            comment_text = form.cleaned_data['text']
            
            comment = Comment(author=comment_author,
                            date=comment_date,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/categories.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'posts/category_detail.html'

posts/templates/posts/categories.html
{% extends 'base.html' %}

{% block title %}
    Categories
{% endblock title %}

{% block content %}
<h2>Categories of posts</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'category_detail' category.id %}"><h3>{{category.name}}</h3></a>
        </header>
    </article>
    {% endfor %}

</section>

{% endblock content %}

posts/templates/posts/category_detail.html
{% extends 'base.html' %}

{% block title %}
    Category
{% endblock title %}

{% block content %}
<div class="lista-de-cards">
    <h2>{{ category.name }}</h2>
    <p> Description: {{ category.text }} </p>
    {% for post in category.posts.all %}
    <article class="card">
        <a href="{% url 'detail' post.id %}"><h2>{{ post.title }} ({{ post.date|date:"SHORT_DATE_FORMAT" }})</h2></a>
        {{ post.text|safe|escape }}
    </article>
    {% endfor %}
</div>
</ul>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comment on {{ post.title }} ({{ post.date|date:"SHORT_DATE_FORMAT" }})</h2>

<form action="{% url 'comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Publish</button>
</form>

<p><a href="{% url 'detail' post.id %}">Return to post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block title %}
    Create
{% endblock title %}

{% block content %}
<h2>Create a new post</h2>
<form method="POST" action="{% url 'create' %}">
    {% csrf_token %}
    <p>
        <label for="id_title">Title:</label>
        <input type="text" name="title" id="id_title" />
    </p>
    <p>
        <label for="id_date">Date:</label>
        <input type="date" name="date" id="id_date" />
    </p>
    <p>
        <label for="id_text">Text:</label>
        <input type="text" name="text" id="id_text" />
    </p>
    <button type="submit">Publish</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete
{% endblock title %}

{% block content %}
<form action="{% url 'delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Are you sure you want to delete this post?
    </p>
    <button type="submit">Delete</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
    Post
{% endblock title %}

{% block content %}
<article class="card">
    <h2>{{ post.title }} ({{ post.date|date:"SHORT_DATE_FORMAT" }})</h2>
    {{ post.text|safe|escape }}
</article>
<div class='box'>
    <p class='custom'>Alternative:</p>
    <ul class='custom'>
        <li class='select'><a href="{% url 'update' post.id %}">Edit</a></li>
        <li class='select'><a href="{% url 'delete' post.id %}">Delete</a></li>
    </ul>
</div>
<div class='box'>
    <p class='custom'>Categories:</p>
    <ul class='custom'>
        {% if post.category_set.all %}
            {% for category in post.category_set.all %}
                <li class='select'><a href="{% url 'category_detail' pk=category.pk %}">{{ category.name }}</a></li>
            {% endfor %}
        {% endif %}
    </ul>
</div>

<section>
    <header>
        <h3>Comment section</h3>
    </header>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }} ({{ comment.date|date:"SHORT_DATE_FORMAT" }})
                </figure>
            {% endfor %}
        {% else %}
            <p>No comment yet.</p>
        {% endif %}
    </ul>
    <a href="{% url 'comment' post.pk %}"><button>Post your comment</button></a>
</section>

{% endblock content %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'detail' post.id %}"><h2>{{ post.title }} ({{ post.date|date:"SHORT_DATE_FORMAT" }})</h2></a>
        {{ post.text|safe|escape }}
    </article>
    {% endfor %}
</section>
{% else %}
<p>No post found.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
    Update
{% endblock title %}

{% block content %}
<h2>Update post {{ post.title }}</h2>
<form method="POST" action="{% url 'update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_title">Title:</label>
        <input type="text" name="title" id="id_title" />
    </p>
    <p>
        <label for="id_date">Date:</label>
        <input type="date" name="date" id="id_date" />
    </p>
    <p>
        <label for="id_text">Text:</label>
        <input type="text" name="text" id="id_text" />
    </p>
    <button type="submit">Publish</button>
</form>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Deeplog
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header class="main-header">
        <a href="{% url 'list' %}">
            <p>Deeplog</p>
            <p>The very best of deep learning in a single blog.</p>
        </a>
    </header>
    <div class="main-header">
        <p> Want to contribute to the Community?<a href="{% url 'create' %}">Post</a></p>
        <p> Want to see the posts organized by categories?<a href="{% url 'categories' %}">Summary</a></p>
    </div>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>